### ISSUE TITLE
`scaffer g app-fs-forms` does not work on Win10 x64 (but works on WSL)

### ISSUE THREAD

**Issue by Marty-Stu** [vivainio/scaffer-templates#2]
```
OS     : Windows 10 x64 Pro 22H2
Python : Python 3.12 [Windows installer (64-bit)] https://www.python.org/downloads/release/python-3121/

[  Ok   ] ...\projects\Fs\TestProj>>scaffer g mit
[ Error ] ...\projects\Fs\TestProj>>scaffer g app-fs-forms
```
```
scaffer g app-fs-forms

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\dev\python\Python312\Scripts\scaffer.exe\__main__.py", line 7, in <module>
  File "C:\dev\python\Python312\Lib\site-packages\scaffer\scaffer.py", line 204, in main
    argp.parse()
  File "C:\dev\python\Python312\Lib\site-packages\argp\argp.py", line 86, in parse
    parse_list(sys.argv[1:])
  File "C:\dev\python\Python312\Lib\site-packages\argp\argp.py", line 66, in parse_list
    dispatch_parsed(parsed)
  File "C:\dev\python\Python312\Lib\site-packages\argp\argp.py", line 73, in dispatch_parsed
    parse_result.func(parse_result)
  File "C:\dev\python\Python312\Lib\site-packages\scaffer\scaffer.py", line 128, in do_gen
    content = list(emitter.files_with_content("."))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\python\Python312\Lib\site-packages\scaffer\emitter.py", line 90, in files_with_content
    if ".git" in dirpath or matches(Path(dirpath).resolve()):
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\python\Python312\Lib\site-packages\gitignore_parser.py", line 33, in <lambda>
    return lambda file_path: handle_negation(file_path, rules)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\python\Python312\Lib\site-packages\gitignore_parser.py", line 11, in handle_negation
    if rule.match(file_path):
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\python\Python312\Lib\site-packages\gitignore_parser.py", line 126, in match
    rel_path = str(_normalize_path(abs_path).relative_to(self.base_path))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\python\Python312\Lib\pathlib.py", line 682, in relative_to
    raise ValueError(f"{str(self)!r} is not in the subpath of {str(other)!r}")
ValueError: 'B:\\D\\R\\proj\\Fs\\scaffer-templates\\templates\\app-fs-forms' is not in the subpath of 
'C:\\Users\\user\\Documents\\projects\\Fs\\scaffer-templates\\templates\\app-fs-forms'
```

**Comment by vivainio** [comment]
The problem likely is that the file is on a different drive
